# Generated by Django 4.2.1 on 2023-07-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phone_contact_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
